# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventoryService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import book_pb2 as book__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16inventoryService.proto\x12\x10inventoryService\x1a\nbook.proto\".\n\x11\x43reateBookRequest\x12\x19\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0b.books.Book\"O\n\x12\x43reateBookResponse\x12(\n\x06status\x18\x01 \x01(\x0e\x32\x18.inventoryService.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\",\n\x0fGetBookResponse\x12\x19\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0b.books.Book*i\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0e\n\nISBN_ERROR\x10\x01\x12\x0f\n\x0bTITLE_ERROR\x10\x02\x12\x10\n\x0c\x41UTHOR_ERROR\x10\x03\x12\x0f\n\x0bGENRE_ERROR\x10\x04\x12\x0e\n\nYEAR_ERROR\x10\x05\x32\xc2\x01\n\x10InventoryService\x12Y\n\nCreateBook\x12#.inventoryService.CreateBookRequest\x1a$.inventoryService.CreateBookResponse\"\x00\x12S\n\x07GetBook\x12 .inventoryService.GetBookRequest\x1a$.inventoryService.CreateBookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventoryService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=263
  _STATUS._serialized_end=368
  _CREATEBOOKREQUEST._serialized_start=56
  _CREATEBOOKREQUEST._serialized_end=102
  _CREATEBOOKRESPONSE._serialized_start=104
  _CREATEBOOKRESPONSE._serialized_end=183
  _GETBOOKREQUEST._serialized_start=185
  _GETBOOKREQUEST._serialized_end=215
  _GETBOOKRESPONSE._serialized_start=217
  _GETBOOKRESPONSE._serialized_end=261
  _INVENTORYSERVICE._serialized_start=371
  _INVENTORYSERVICE._serialized_end=565
# @@protoc_insertion_point(module_scope)
